// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddTodo: typeof import('./src/components/todo/AddTodo.vue')['default']
    Interface: typeof import('./src/components/todo/interface/index.ts')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Todo: typeof import('./src/components/todo/Todo.vue')['default']
    'Todo.interface': typeof import('./src/components/todo/interface/todo.interface.ts')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
  }
}

export { }
